# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ATMCardTypeDetectDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "CreditCardForm"
  pod "Stripe"
  # Pods for ATMCardTypeDetectDemo

  target 'ATMCardTypeDetectDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ATMCardTypeDetectDemoUITests' do
    # Pods for testing
  end

end
